import jsPDF from 'jspdf';
import { PDF_CONFIG, getUsablePageDimensions, formatPDFDate } from './config';

// Helper function to split text into lines that fit the page width
export const splitTextToFitWidth = (
  doc: jsPDF, 
  text: string, 
  maxWidth: number, 
  fontSize: number = PDF_CONFIG.bodySize
): string[] => {
  doc.setFontSize(fontSize);
  return doc.splitTextToSize(text, maxWidth);
};

// Helper function to add a new page if needed
export const checkAndAddPage = (doc: jsPDF, currentY: number, requiredHeight: number): number => {
  const { height } = getUsablePageDimensions();
  if (currentY + requiredHeight > height + PDF_CONFIG.margins.top) {
    doc.addPage();
    return PDF_CONFIG.margins.top;
  }
  return currentY;
};

// Helper function to add page header
export const addPageHeader = (doc: jsPDF, title: string, subtitle?: string): number => {
  const { width } = getUsablePageDimensions();
  
  // Title
  doc.setFontSize(PDF_CONFIG.titleSize);
  doc.setFont('helvetica', 'bold');
  doc.text(title, PDF_CONFIG.margins.left, PDF_CONFIG.margins.top);
  
  let currentY = PDF_CONFIG.margins.top + PDF_CONFIG.lineHeight * 2;
  
  // Subtitle if provided
  if (subtitle) {
    doc.setFontSize(PDF_CONFIG.headerSize);
    doc.setFont('helvetica', 'normal');
    doc.text(subtitle, PDF_CONFIG.margins.left, currentY);
    currentY += PDF_CONFIG.lineHeight * 1.5;
  }
  
  // Date and line separator
  doc.setFontSize(PDF_CONFIG.bodySize);
  doc.setFont('helvetica', 'normal');
  const dateText = `Generated on: ${formatPDFDate()}`;
  doc.text(dateText, PDF_CONFIG.margins.left, currentY);
  
  currentY += PDF_CONFIG.lineHeight;
  
  // Horizontal line
  doc.setLineWidth(0.5);
  doc.line(
    PDF_CONFIG.margins.left, 
    currentY, 
    PDF_CONFIG.margins.left + width, 
    currentY
  );
  
  return currentY + PDF_CONFIG.lineHeight;
};

// Helper function to add page footer
export const addPageFooter = (doc: jsPDF): void => {
  const pageCount = doc.getCurrentPageInfo().pageNumber;
  const totalPages = doc.getNumberOfPages();
  
  doc.setFontSize(PDF_CONFIG.codeSize);
  doc.setFont('helvetica', 'normal');
  
  // Footer text
  const footerText = `Page ${pageCount} of ${totalPages} - Generated by Legal Document Simplification Platform`;
  const textWidth = doc.getTextWidth(footerText);
  const { width } = getUsablePageDimensions();
  
  doc.text(
    footerText,
    PDF_CONFIG.margins.left + (width - textWidth) / 2,
    PDF_CONFIG.pageHeight - PDF_CONFIG.margins.bottom + 5
  );
};

// Helper function to add footers to all pages
export const addFootersToAllPages = (doc: jsPDF): void => {
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addPageFooter(doc);
  }
};